### ISSUE TITLE
LSTM?

### ISSUE THREAD

**Issue by r0nn13** [breze-no-salt/breze#74]
What happened to the SupervisedLstmRnn?

**Comment by bayerj** [comment]
It can be used by using a SupervisedRnn and specifying "lstm" as transfer function. That was done to remove code duplication, but required certrain changes for transfer functions.

**Comment by r0nn13** [comment]
Thanks!



<div>-------- Original message --------</div><div>From: Justin Bayer <notifications@github.com> </div><div>Date:09/27/2015  19:00  (GMT+00:00) </div><div>To: breze-no-salt/breze <breze@noreply.github.com> </div><div>Cc: Ronnie Clark <ron.clark@live.com> </div><div>Subject: Re: [breze] LSTM? (#74) </div><div>
</div>
It can be used by using a SupervisedRnn and specifying "lstm" as transfer function. That was done to remove code duplication, but required certrain changes for transfer functions.

---
